esphome:
  name: arduino
  
esp32:
  board: m5stack-atom
  framework:
    type: arduino
  compile_flags:
  - -DLWIP_IPV6_HOOK=1
  - -Dlwip_hook_ip6_input=NULL

external_components:
  - source: 
      type: local
      path: /github/workspace/components
    
uart:
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 9600
  parity: EVEN

samsung_ac:  
  debug_log_messages: false
  debug_log_messages_raw: false

  devices:
  - address: "20.00.00"
    climate:
      name: "Test"  
    room_temperature:
      name: Test1_temp
    target_temperature:
      name: Test1_target
    power:
      name: Test1_power
